table Calendar
	excludeFromModelRefresh
	lineageTag: 1c1a71bb-0015-435d-b466-ef62d080219f

	column date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 70b06602-ac37-4741-a2b4-d6b8f5b0567b
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 5be8feaf-817a-4912-8cd0-798015a20d8a
			defaultHierarchy: LocalDateTable_28e33e20-8e94-4169-87fd-156111a50628.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Start of Week'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 9fb48576-9276-4f8b-8353-64869ea10d85
		summarizeBy: none
		sourceColumn: Start of Week

		variation Variation
			isDefault
			relationship: 2fa34afd-b84b-4d41-b3f1-9b9a2586193b
			defaultHierarchy: LocalDateTable_b6e96c81-cff6-4754-9dc1-2ce360c303e5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Day Name'
		dataType: string
		lineageTag: 1e2a2d40-b2bd-4d55-ab1f-db0d7e7783be
		summarizeBy: none
		sourceColumn: Day Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Start of Month'
		dataType: dateTime
		formatString: Short Date
		lineageTag: bdd39da2-5e5a-4204-97f6-d0bca9e4e472
		summarizeBy: none
		sourceColumn: Start of Month

		variation Variation
			isDefault
			relationship: cedd1260-7ae9-419d-bd84-1e75c9efe7b9
			defaultHierarchy: LocalDateTable_057a5fc6-2071-48ec-a5c0-3a214855d2e7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month Name'
		dataType: string
		lineageTag: d9b10fc3-d65c-430b-a97a-746dfbf94bb7
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: e4a9e672-0265-41e6-bef3-ea9dc9fc98c2
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 212cc375-f3c9-4c73-8e72-ce47bc101e96
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Weekend = IF('Calendar'[Day Name] = "Saturday" || 'Calendar'[Day Name] = "Sunday", "Y", "N")
		lineageTag: 68618b79-c379-473d-95a9-0b8625d721a7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'End of Month' = EOMONTH('Calendar'[date],0)
		formatString: Short Date
		lineageTag: 6df6e1b0-2768-4593-8a68-b33b85a16d6c
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 7c511a9f-3b6f-4d50-97b3-3de248736434
			defaultHierarchy: LocalDateTable_1b067b7e-cf3f-4c03-8025-4e11669d5409.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition Calendar-fd89f113-9fda-4395-ad58-0d1061bde5c0 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Chris\Documents\SecondLens\Excel Maven\Udemy\Course 5 - Power BI Desktop\Final Resources\Maven Market\MavenMarket_Calendar.csv"),[Delimiter=",", Columns=1, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"date", type date}}),
				    #"Inserted Start of Week" = Table.AddColumn(#"Changed Type", "Start of Week", each Date.StartOfWeek([date]), type date),
				    #"Inserted Day Name" = Table.AddColumn(#"Inserted Start of Week", "Day Name", each Date.DayOfWeekName([date]), type text),
				    #"Inserted Start of Month" = Table.AddColumn(#"Inserted Day Name", "Start of Month", each Date.StartOfMonth([date]), type date),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Start of Month", "Month Name", each Date.MonthName([date]), type text),
				    #"Inserted Quarter" = Table.AddColumn(#"Inserted Month Name", "Quarter", each Date.QuarterOfYear([date]), Int64.Type),
				    #"Inserted Year" = Table.AddColumn(#"Inserted Quarter", "Year", each Date.Year([date]), Int64.Type)
				in
				    #"Inserted Year"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

