table Calendar
	excludeFromModelRefresh
	lineageTag: 2efdca06-74b4-4ee7-bda2-612d2d3b9900

	column date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 9acb57f6-c2ff-4891-b00a-66a05b4fd0e9
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 5be8feaf-817a-4912-8cd0-798015a20d8a
			defaultHierarchy: LocalDateTable_28e33e20-8e94-4169-87fd-156111a50628.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Start of Week'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 33777154-8841-41cf-b750-78f97b3a9f0b
		summarizeBy: none
		sourceColumn: Start of Week

		variation Variation
			isDefault
			relationship: 2fa34afd-b84b-4d41-b3f1-9b9a2586193b
			defaultHierarchy: LocalDateTable_b6e96c81-cff6-4754-9dc1-2ce360c303e5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Day Name'
		dataType: string
		lineageTag: 4a3660db-39e3-4e77-bd7e-e91334e76ed2
		summarizeBy: none
		sourceColumn: Day Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Start of Month'
		dataType: dateTime
		formatString: Short Date
		lineageTag: a15c1b98-fa96-48cf-9389-c3dd6fd9c0a0
		summarizeBy: none
		sourceColumn: Start of Month

		variation Variation
			isDefault
			relationship: cedd1260-7ae9-419d-bd84-1e75c9efe7b9
			defaultHierarchy: LocalDateTable_057a5fc6-2071-48ec-a5c0-3a214855d2e7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month Name'
		dataType: string
		lineageTag: 3c96bf40-8637-42d5-a08a-5904b230cd4f
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: c4cd631b-1b78-40d0-b51e-27290f77fbe0
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 1a08136b-8118-4357-807f-cb44662791d5
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Weekend = IF('Calendar'[Day Name] = "Saturday" || 'Calendar'[Day Name] = "Sunday", "Y", "N")
		lineageTag: 71dc9f11-250f-4864-a210-70b8eb982142
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'End of Month' = EOMONTH('Calendar'[date],0)
		formatString: Short Date
		lineageTag: 316055ba-ab08-48cd-a18a-be24e2bdfb5d
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 7c511a9f-3b6f-4d50-97b3-3de248736434
			defaultHierarchy: LocalDateTable_1b067b7e-cf3f-4c03-8025-4e11669d5409.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition Calendar-fd89f113-9fda-4395-ad58-0d1061bde5c0 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Chris\Documents\SecondLens\Excel Maven\Udemy\Course 5 - Power BI Desktop\Final Resources\Maven Market\MavenMarket_Calendar.csv"),[Delimiter=",", Columns=1, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"date", type date}}),
				    #"Inserted Start of Week" = Table.AddColumn(#"Changed Type", "Start of Week", each Date.StartOfWeek([date]), type date),
				    #"Inserted Day Name" = Table.AddColumn(#"Inserted Start of Week", "Day Name", each Date.DayOfWeekName([date]), type text),
				    #"Inserted Start of Month" = Table.AddColumn(#"Inserted Day Name", "Start of Month", each Date.StartOfMonth([date]), type date),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Start of Month", "Month Name", each Date.MonthName([date]), type text),
				    #"Inserted Quarter" = Table.AddColumn(#"Inserted Month Name", "Quarter", each Date.QuarterOfYear([date]), Int64.Type),
				    #"Inserted Year" = Table.AddColumn(#"Inserted Quarter", "Year", each Date.Year([date]), Int64.Type)
				in
				    #"Inserted Year"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

