table Customers
	excludeFromModelRefresh
	lineageTag: e3eb8f61-41b6-4559-82db-c4c9fdb07fee

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: 925d0858-12a5-49ba-840e-93bfa5f6e25d
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_acct_num
		dataType: string
		lineageTag: a4e7f47a-dd2a-4322-99e8-03a673927616
		summarizeBy: none
		sourceColumn: customer_acct_num

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column first_name
		dataType: string
		lineageTag: f5aa62fa-230c-4620-a5d0-638858dee535
		summarizeBy: none
		sourceColumn: first_name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column last_name
		dataType: string
		lineageTag: 9d97f77f-976b-43b4-9d33-57ade5f6ea9c
		summarizeBy: none
		sourceColumn: last_name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column customer_address
		dataType: string
		lineageTag: 34324ee9-c311-4fb4-b669-5556f44b3b70
		summarizeBy: none
		sourceColumn: customer_address

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column customer_city
		dataType: string
		lineageTag: 20474a02-bbf0-457e-886f-6ad6001b1464
		dataCategory: City
		summarizeBy: none
		sourceColumn: customer_city

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column customer_state_province
		dataType: string
		lineageTag: b729aae4-e454-4099-b419-b35d068a82b3
		summarizeBy: none
		sourceColumn: customer_state_province

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column customer_postal_code
		dataType: string
		lineageTag: 6839ab6f-3453-41c5-877b-60977082cb0e
		dataCategory: PostalCode
		summarizeBy: none
		sourceColumn: customer_postal_code

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column customer_country
		dataType: string
		lineageTag: 2938b326-eed9-47a5-a994-71f9ea30a967
		dataCategory: Country
		summarizeBy: none
		sourceColumn: customer_country

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column birthdate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 70dc0eba-c585-4f15-9887-be2797aa2b79
		summarizeBy: none
		sourceColumn: birthdate

		variation Variation
			isDefault
			relationship: 7b96ac4e-aafe-40c4-985d-e27d16f3e6b2
			defaultHierarchy: LocalDateTable_c5a3a9d6-4c73-4de9-b37b-a0dc9d8b563a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column marital_status
		dataType: string
		lineageTag: 17223c91-8db5-40b3-b95a-609f260b4eba
		summarizeBy: none
		sourceColumn: marital_status

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column yearly_income
		dataType: string
		lineageTag: 4e94f7c5-4ab5-4f09-a140-a29c1934e75a
		summarizeBy: none
		sourceColumn: yearly_income

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column gender
		dataType: string
		lineageTag: e6bb7b9c-7b6f-4b33-9ab4-ef9f30439794
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column total_children
		dataType: int64
		formatString: 0
		lineageTag: 0108c92e-206e-49fc-9346-9e434bc6c8fd
		summarizeBy: sum
		sourceColumn: total_children

		annotation SummarizationSetBy = Automatic

	column num_children_at_home
		dataType: int64
		formatString: 0
		lineageTag: 06c36e1c-dd41-4885-928d-23d9a05b04a9
		summarizeBy: sum
		sourceColumn: num_children_at_home

		annotation SummarizationSetBy = Automatic

	column education
		dataType: string
		lineageTag: 1aa37d97-079b-43c8-80e4-1c08b5569bc3
		summarizeBy: none
		sourceColumn: education

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column acct_open_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: faec5ebd-fb7d-474d-930a-3727e16b90e6
		summarizeBy: none
		sourceColumn: acct_open_date

		variation Variation
			isDefault
			relationship: d621e994-1174-4115-9eda-17adddd90fa1
			defaultHierarchy: LocalDateTable_fe5a205d-33f0-43f0-bde9-d805094d7108.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column member_card
		dataType: string
		lineageTag: 9935fb38-0a91-47ac-81c9-9b3a878ef631
		summarizeBy: none
		sourceColumn: member_card

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column occupation
		dataType: string
		lineageTag: a1be66b9-9e0d-4da3-b154-0c7eee0ad9d9
		summarizeBy: none
		sourceColumn: occupation

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column homeowner
		dataType: string
		lineageTag: 427041d7-ca05-4e1b-ae1f-4eeee637e29e
		summarizeBy: none
		sourceColumn: homeowner

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column full_name
		dataType: string
		lineageTag: 018b87bb-ee11-4d9b-ab18-92b573c0c316
		summarizeBy: none
		sourceColumn: full_name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column birth_year
		dataType: int64
		formatString: 0
		lineageTag: 105ae2c6-2173-4ceb-81ac-65cf75e99805
		summarizeBy: sum
		sourceColumn: birth_year

		annotation SummarizationSetBy = Automatic

	column has_children
		dataType: string
		lineageTag: 1b9381d2-933a-4d62-8519-30d419022632
		summarizeBy: none
		sourceColumn: has_children

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Current_Age = DATEDIFF(Customers[birthdate],TODAY(),YEAR)
		formatString: 0
		lineageTag: 5556bc91-e710-4178-a25b-2e1079ed745c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Priority = IF(Customers[member_card] = "Golden" && Customers[homeowner] = "Y","High","Standard")
		lineageTag: 5fd4df37-d4b5-45db-8e05-01f626693be8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Short_Country = UPPER(LEFT(Customers[customer_country],3))
		lineageTag: 131b2289-4dd6-4197-aa30-b72e3b20c2be
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column House_Number = LEFT(Customers[customer_address], SEARCH(" ", Customers[customer_address])-1)
		lineageTag: 01a40afa-dc32-4420-baad-b4c9c124b9fc
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition Customers-06ce47fd-0986-4c0a-b7fb-60681980529d = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Chris\Documents\SecondLens\Excel Maven\Udemy\Course 5 - Power BI Desktop\Final Resources\Maven Market\MavenMarket_Customers.csv"),[Delimiter=",", Columns=20, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", Int64.Type}, {"customer_acct_num", type text}, {"first_name", type text}, {"last_name", type text}, {"customer_address", type text}, {"customer_city", type text}, {"customer_state_province", type text}, {"customer_postal_code", type text}, {"customer_country", type text}, {"birthdate", type date}, {"marital_status", type text}, {"yearly_income", type text}, {"gender", type text}, {"total_children", Int64.Type}, {"num_children_at_home", Int64.Type}, {"education", type text}, {"acct_open_date", type date}, {"member_card", type text}, {"occupation", type text}, {"homeowner", type text}}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Changed Type", "full_name", each Text.Combine({[first_name], [last_name]}, " "), type text),
				    #"Inserted Year" = Table.AddColumn(#"Inserted Merged Column", "Year", each Date.Year([birthdate]), Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Year",{{"Year", "birth_year"}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Renamed Columns", "has_children", each if [total_children] = 0 then "N" else "Y")
				in
				    #"Added Conditional Column"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

