table Customers
	excludeFromModelRefresh
	lineageTag: 66ea6cd0-afd9-4cee-ba4a-605c31b593bf

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: 363d812a-6416-4ebb-a4ab-67d837d8b6cf
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_acct_num
		dataType: string
		lineageTag: ca06e57c-3342-4409-acc3-dee621a29e42
		summarizeBy: none
		sourceColumn: customer_acct_num

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column first_name
		dataType: string
		lineageTag: f7810813-8f69-434e-b5ee-75199e85d8cd
		summarizeBy: none
		sourceColumn: first_name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column last_name
		dataType: string
		lineageTag: e0cc5c00-0a5f-4b96-9ca0-dc9a2a5e9a35
		summarizeBy: none
		sourceColumn: last_name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column customer_address
		dataType: string
		lineageTag: 5fadbfb3-4689-4aa8-b9c6-bbffa6bdffe9
		summarizeBy: none
		sourceColumn: customer_address

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column customer_city
		dataType: string
		lineageTag: b038fdaf-9114-46e3-89ad-4785a75d75e9
		dataCategory: City
		summarizeBy: none
		sourceColumn: customer_city

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column customer_state_province
		dataType: string
		lineageTag: 054cfe13-0969-4752-a95f-2309cafa072c
		summarizeBy: none
		sourceColumn: customer_state_province

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column customer_postal_code
		dataType: string
		lineageTag: bfa302c1-3626-4234-8d27-3c7816908d70
		dataCategory: PostalCode
		summarizeBy: none
		sourceColumn: customer_postal_code

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column customer_country
		dataType: string
		lineageTag: 27cb984c-f434-4ef8-9991-606bff11441b
		dataCategory: Country
		summarizeBy: none
		sourceColumn: customer_country

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column birthdate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 67855a9f-523f-4825-8495-f4f42593b8ba
		summarizeBy: none
		sourceColumn: birthdate

		variation Variation
			isDefault
			relationship: 7b96ac4e-aafe-40c4-985d-e27d16f3e6b2
			defaultHierarchy: LocalDateTable_c5a3a9d6-4c73-4de9-b37b-a0dc9d8b563a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column marital_status
		dataType: string
		lineageTag: a64e3221-4564-4276-ad58-b8cb860d7f1f
		summarizeBy: none
		sourceColumn: marital_status

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column yearly_income
		dataType: string
		lineageTag: 945b6356-e117-46ba-bd77-2b14f707b00d
		summarizeBy: none
		sourceColumn: yearly_income

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column gender
		dataType: string
		lineageTag: d386ac9f-eadf-4724-b99f-75929e40689a
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column total_children
		dataType: int64
		formatString: 0
		lineageTag: 7e969c9c-2147-4264-b2f8-8e693f7addaa
		summarizeBy: sum
		sourceColumn: total_children

		annotation SummarizationSetBy = Automatic

	column num_children_at_home
		dataType: int64
		formatString: 0
		lineageTag: 5c330b01-8f35-46db-a092-b13999d486c3
		summarizeBy: sum
		sourceColumn: num_children_at_home

		annotation SummarizationSetBy = Automatic

	column education
		dataType: string
		lineageTag: 87366a5b-3049-4370-8f94-855106389df9
		summarizeBy: none
		sourceColumn: education

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column acct_open_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 4f321004-1c31-41b2-8310-40c64ad77c52
		summarizeBy: none
		sourceColumn: acct_open_date

		variation Variation
			isDefault
			relationship: d621e994-1174-4115-9eda-17adddd90fa1
			defaultHierarchy: LocalDateTable_fe5a205d-33f0-43f0-bde9-d805094d7108.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column member_card
		dataType: string
		lineageTag: 29ebdfca-b773-4d60-81fa-44aa0911582e
		summarizeBy: none
		sourceColumn: member_card

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column occupation
		dataType: string
		lineageTag: 6c67b69a-d386-4c05-a816-a80fa4e9e8ef
		summarizeBy: none
		sourceColumn: occupation

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column homeowner
		dataType: string
		lineageTag: 7bd814c5-1d03-4843-b94c-a0210792c7b6
		summarizeBy: none
		sourceColumn: homeowner

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column full_name
		dataType: string
		lineageTag: f8c1ca28-d987-4e3f-b133-233ab91d0672
		summarizeBy: none
		sourceColumn: full_name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column birth_year
		dataType: int64
		formatString: 0
		lineageTag: b871ee9e-23f1-4282-9d01-80e2695c2964
		summarizeBy: sum
		sourceColumn: birth_year

		annotation SummarizationSetBy = Automatic

	column has_children
		dataType: string
		lineageTag: cb1e25a2-ca9f-4744-a3e9-ff29a4bf8df6
		summarizeBy: none
		sourceColumn: has_children

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Current_Age = DATEDIFF(Customers[birthdate],TODAY(),YEAR)
		formatString: 0
		lineageTag: 3a5e2f58-401a-4bd6-89d6-2c2f07b76af3
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Priority = IF(Customers[member_card] = "Golden" && Customers[homeowner] = "Y","High","Standard")
		lineageTag: 5a63a17d-a4ba-4b36-87a8-2dd99b7261a7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Short_Country = UPPER(LEFT(Customers[customer_country],3))
		lineageTag: 16217273-9d40-43bb-aaf5-c40996959d54
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column House_Number = LEFT(Customers[customer_address], SEARCH(" ", Customers[customer_address])-1)
		lineageTag: 3cb71163-e6bc-4931-a591-0e43b3d54c83
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition Customers-06ce47fd-0986-4c0a-b7fb-60681980529d = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Chris\Documents\SecondLens\Excel Maven\Udemy\Course 5 - Power BI Desktop\Final Resources\Maven Market\MavenMarket_Customers.csv"),[Delimiter=",", Columns=20, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", Int64.Type}, {"customer_acct_num", type text}, {"first_name", type text}, {"last_name", type text}, {"customer_address", type text}, {"customer_city", type text}, {"customer_state_province", type text}, {"customer_postal_code", type text}, {"customer_country", type text}, {"birthdate", type date}, {"marital_status", type text}, {"yearly_income", type text}, {"gender", type text}, {"total_children", Int64.Type}, {"num_children_at_home", Int64.Type}, {"education", type text}, {"acct_open_date", type date}, {"member_card", type text}, {"occupation", type text}, {"homeowner", type text}}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Changed Type", "full_name", each Text.Combine({[first_name], [last_name]}, " "), type text),
				    #"Inserted Year" = Table.AddColumn(#"Inserted Merged Column", "Year", each Date.Year([birthdate]), Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Year",{{"Year", "birth_year"}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Renamed Columns", "has_children", each if [total_children] = 0 then "N" else "Y")
				in
				    #"Added Conditional Column"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

