table Products
	excludeFromModelRefresh
	lineageTag: 88b38a33-9696-4dac-b60f-dc71cdd33b60

	measure 'Unique Products' = DISTINCTCOUNT(Products[product_name])
		formatString: 0
		lineageTag: 50409af8-41fd-4f20-9eba-2f680ae4d6d8

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: f186fe18-9b76-49bc-8867-0b7cd6fc8fb6
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column product_brand
		dataType: string
		lineageTag: 085ab79f-ba5b-4fef-82d5-06e2b3cbe182
		summarizeBy: none
		sourceColumn: product_brand

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column product_name
		dataType: string
		lineageTag: 6eac0b6f-4fbf-4fed-8f2b-78461e416258
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column product_sku
		dataType: double
		lineageTag: 251cc8f4-cf8f-421a-935c-09e21cd9f399
		summarizeBy: sum
		sourceColumn: product_sku

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column product_retail_price
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: eb1300fb-41d5-4b8d-86d9-91cdfec2041e
		summarizeBy: sum
		sourceColumn: product_retail_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column product_cost
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: b7556364-c5ac-4a51-89b3-bc70cbe76e54
		summarizeBy: sum
		sourceColumn: product_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column product_weight
		dataType: double
		lineageTag: 8441e7d1-add0-480f-9bc8-becab54247ce
		summarizeBy: sum
		sourceColumn: product_weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column recyclable
		dataType: int64
		formatString: 0
		lineageTag: c95889da-f721-434d-823c-024a7198119e
		summarizeBy: sum
		sourceColumn: recyclable

		annotation SummarizationSetBy = Automatic

	column low_fat
		dataType: int64
		formatString: 0
		lineageTag: 972cd989-503a-498a-b72a-3fe1686f5923
		summarizeBy: sum
		sourceColumn: low_fat

		annotation SummarizationSetBy = Automatic

	column discount_price
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 2e56037a-1246-4b86-8fa8-ee8324cbb876
		summarizeBy: sum
		sourceColumn: discount_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Price_Tier = IF(Products[product_retail_price]>3, "High", IF(Products[product_retail_price]>1, "Mid", "Low"))
		lineageTag: a1b8aa3f-48e1-4f54-9063-226c12c6ad4a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition Products-b6c50b4f-ce8d-4c1d-8594-51e91b244b18 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Chris\Documents\SecondLens\Excel Maven\Udemy\Course 5 - Power BI Desktop\Final Resources\Maven Market\MavenMarket_Products.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"product_id", Int64.Type}, {"product_brand", type text}, {"product_name", type text}, {"product_sku", type number}, {"product_retail_price", type number}, {"product_cost", type number}, {"product_weight", type number}, {"recyclable", Int64.Type}, {"low_fat", Int64.Type}}),
				    #"Inserted Multiplication" = Table.AddColumn(#"Changed Type", "Multiplication", each [product_retail_price] * 0.9, type number),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Multiplication",{{"Multiplication", "discount_price"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"discount_price", Currency.Type}}),
				    #"Rounded Off" = Table.TransformColumns(#"Changed Type1",{{"discount_price", each Number.Round(_, 2), Currency.Type}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Rounded Off",null,0,Replacer.ReplaceValue,{"recyclable"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",null,0,Replacer.ReplaceValue,{"low_fat"})
				in
				    #"Replaced Value1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

