table Products
	excludeFromModelRefresh
	lineageTag: 655b038d-e922-496e-a652-abe7ed320feb

	measure 'Unique Products' = DISTINCTCOUNT(Products[product_name])
		formatString: 0
		lineageTag: 55cb7939-e05d-4ae4-9497-fe845bb0962a

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: 303162f1-b7e5-4617-808e-34a927798b4f
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column product_brand
		dataType: string
		lineageTag: 456f3da4-545c-4027-97e5-d2205f96ceba
		summarizeBy: none
		sourceColumn: product_brand

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column product_name
		dataType: string
		lineageTag: 0c1a1a32-6c2a-40c4-ae38-9641d067e6a4
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column product_sku
		dataType: double
		lineageTag: ae519aa2-628c-44e0-9fad-58c177fe73fa
		summarizeBy: sum
		sourceColumn: product_sku

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column product_retail_price
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: ca4391c8-d1b9-477e-9bee-f0567fd8f9d2
		summarizeBy: sum
		sourceColumn: product_retail_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column product_cost
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 713bfab4-dbc9-4f7e-829c-75c4dbee7a4e
		summarizeBy: sum
		sourceColumn: product_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column product_weight
		dataType: double
		lineageTag: af8b3ce3-4384-4783-8170-aed9a8c156cb
		summarizeBy: sum
		sourceColumn: product_weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column recyclable
		dataType: int64
		formatString: 0
		lineageTag: a1862edb-9539-4575-a1b6-d5deeef78330
		summarizeBy: sum
		sourceColumn: recyclable

		annotation SummarizationSetBy = Automatic

	column low_fat
		dataType: int64
		formatString: 0
		lineageTag: c1ec0e8d-1ae5-448c-baec-c5be39d98a1f
		summarizeBy: sum
		sourceColumn: low_fat

		annotation SummarizationSetBy = Automatic

	column discount_price
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: bbec0585-7311-49fb-96c5-878654c56b92
		summarizeBy: sum
		sourceColumn: discount_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Price_Tier = IF(Products[product_retail_price]>3, "High", IF(Products[product_retail_price]>1, "Mid", "Low"))
		lineageTag: eed0acd8-61e1-442b-8f08-bb31c8d69c12
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition Products-b6c50b4f-ce8d-4c1d-8594-51e91b244b18 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Chris\Documents\SecondLens\Excel Maven\Udemy\Course 5 - Power BI Desktop\Final Resources\Maven Market\MavenMarket_Products.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"product_id", Int64.Type}, {"product_brand", type text}, {"product_name", type text}, {"product_sku", type number}, {"product_retail_price", type number}, {"product_cost", type number}, {"product_weight", type number}, {"recyclable", Int64.Type}, {"low_fat", Int64.Type}}),
				    #"Inserted Multiplication" = Table.AddColumn(#"Changed Type", "Multiplication", each [product_retail_price] * 0.9, type number),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Multiplication",{{"Multiplication", "discount_price"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"discount_price", Currency.Type}}),
				    #"Rounded Off" = Table.TransformColumns(#"Changed Type1",{{"discount_price", each Number.Round(_, 2), Currency.Type}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Rounded Off",null,0,Replacer.ReplaceValue,{"recyclable"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",null,0,Replacer.ReplaceValue,{"low_fat"})
				in
				    #"Replaced Value1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

