table Regions
	excludeFromModelRefresh
	lineageTag: 5d7429f8-6ff5-468b-a208-1873ebb70654

	column region_id
		dataType: int64
		formatString: 0
		lineageTag: 1c90402d-6ec4-44d0-8319-c80bdf358e4c
		summarizeBy: none
		sourceColumn: region_id

		annotation SummarizationSetBy = Automatic

	column sales_district
		dataType: string
		lineageTag: a09717ad-07cc-4b75-a9ea-9dfc69fa2da4
		summarizeBy: none
		sourceColumn: sales_district

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column sales_region
		dataType: string
		lineageTag: e7016db5-71a7-4e42-8d6d-e528a60b69eb
		summarizeBy: none
		sourceColumn: sales_region

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition Regions-7d79bf32-5383-4a2e-b645-3b4c2dde808f = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Chris\Documents\SecondLens\Excel Maven\Udemy\Course 5 - Power BI Desktop\Final Resources\Maven Market\MavenMarket_Regions.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"region_id", Int64.Type}, {"sales_district", type text}, {"sales_region", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

