table Regions
	excludeFromModelRefresh
	lineageTag: 6d018b5d-c37a-4de8-af28-b6cfaea9685b

	column region_id
		dataType: int64
		formatString: 0
		lineageTag: 32a52ce8-cb1b-44b6-b832-dc01659a14fb
		summarizeBy: none
		sourceColumn: region_id

		annotation SummarizationSetBy = Automatic

	column sales_district
		dataType: string
		lineageTag: ef71605e-b26e-45d5-8107-e8dc5f065238
		summarizeBy: none
		sourceColumn: sales_district

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column sales_region
		dataType: string
		lineageTag: 33ed7cbc-d6d0-4526-9e0f-91453e316e04
		summarizeBy: none
		sourceColumn: sales_region

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition Regions-7d79bf32-5383-4a2e-b645-3b4c2dde808f = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Chris\Documents\SecondLens\Excel Maven\Udemy\Course 5 - Power BI Desktop\Final Resources\Maven Market\MavenMarket_Regions.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"region_id", Int64.Type}, {"sales_district", type text}, {"sales_region", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

