table Return_Data
	lineageTag: 631b219a-9fb9-45e0-9733-42bae69484a7

	measure 'Quantity Returned' = SUM(Return_Data[quantity])
		formatString: 0
		lineageTag: 05cea1b8-072d-4f6b-8af4-12df556c90a6

	measure 'Total Returns' = COUNTROWS(Return_Data)
		formatString: 0
		lineageTag: 90df6dc3-241b-4ea1-b540-49b8680c9d56

	measure 'Return Rate' = [Quantity Returned] / [Quantity Sold]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 81da9136-aeee-4662-9f1c-b1dd9dbdad10

	measure 'All Returns' = CALCULATE([Total Returns], ALL(Return_Data))
		formatString: 0
		lineageTag: 4503fd68-252b-4d7f-9f82-00bb3a9b945f

	measure 'Last Month Returns' = CALCULATE([Total Returns], DATEADD('Calendar'[date],-1,MONTH))
		formatString: 0
		lineageTag: 974eadd4-bc11-4c48-8226-84d91a17b0fc

	column return_date
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: 9f116b10-a860-4af0-b253-028e1cbe0689
		summarizeBy: none
		sourceColumn: return_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column product_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 636aab63-9d2d-48d2-846a-82133ee2cb04
		summarizeBy: none
		sourceColumn: product_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column store_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 866cfc81-9659-4605-b5fe-d8fa095fc220
		summarizeBy: none
		sourceColumn: store_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: b2b76268-2631-4aec-9210-b92520bf1044
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	partition Return_Data-b0adeb10-1025-4768-b080-9727e32d2118 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Chris\Documents\SecondLens\Excel Maven\Udemy\Course 5 - Power BI Desktop\Final Resources\Maven Market\MavenMarket_Returns_1997-1998.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"return_date", type date}, {"product_id", Int64.Type}, {"store_id", Int64.Type}, {"quantity", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

