table Return_Data
	lineageTag: c2dec22f-0a2e-4103-a4b6-75b92401d512

	measure 'Quantity Returned' = SUM(Return_Data[quantity])
		formatString: 0
		lineageTag: a62c3ed1-a432-40e3-9f74-baf0bc5988b3

	measure 'Total Returns' = COUNTROWS(Return_Data)
		formatString: 0
		lineageTag: de0ffdf0-4a25-4ff9-8a7d-d14b5e5d5997

	measure 'Return Rate' = [Quantity Returned] / [Quantity Sold]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6b2f8871-aa84-4a34-8394-d62e8aef0696

	measure 'All Returns' = CALCULATE([Total Returns], ALL(Return_Data))
		formatString: 0
		lineageTag: b8898b54-6328-473a-909b-208c225b951b

	measure 'Last Month Returns' = CALCULATE([Total Returns], DATEADD('Calendar'[date],-1,MONTH))
		formatString: 0
		lineageTag: 29fbb518-79a4-417a-bf50-4ba7d6509cfe

	column return_date
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: 527c5b2f-63bf-40df-8039-540d3956314f
		summarizeBy: none
		sourceColumn: return_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column product_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 50f9b8f4-82ba-4da5-b94d-d815043c9b83
		summarizeBy: none
		sourceColumn: product_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column store_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e12278c9-3179-4398-a981-4e18ce735b1b
		summarizeBy: none
		sourceColumn: store_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: f01c62c7-0ba1-4fbc-9ffd-b17400318d86
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	partition Return_Data-b0adeb10-1025-4768-b080-9727e32d2118 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Chris\Documents\SecondLens\Excel Maven\Udemy\Course 5 - Power BI Desktop\Final Resources\Maven Market\MavenMarket_Returns_1997-1998.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"return_date", type date}, {"product_id", Int64.Type}, {"store_id", Int64.Type}, {"quantity", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

