table Stores
	excludeFromModelRefresh
	lineageTag: 6bb9e6dd-f357-4368-ab9f-d5501a687fa0

	column store_id
		dataType: int64
		formatString: 0
		lineageTag: c94b3de4-deb3-40b7-acd3-1b04cfc49640
		summarizeBy: none
		sourceColumn: store_id

		annotation SummarizationSetBy = Automatic

	column region_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e512e627-a882-42b8-9595-bdab37b1c675
		summarizeBy: none
		sourceColumn: region_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column store_type
		dataType: string
		lineageTag: 67e3e1fc-fb36-4bc2-a9f4-5f7576828bdc
		summarizeBy: none
		sourceColumn: store_type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column store_name
		dataType: string
		lineageTag: b91b3354-cf72-45b2-9382-eea6a3796693
		summarizeBy: none
		sourceColumn: store_name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column store_street_address
		dataType: string
		lineageTag: 5e853cbd-da19-48f7-a20d-8ffeece85b03
		summarizeBy: none
		sourceColumn: store_street_address

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column store_city
		dataType: string
		lineageTag: 346b5ae8-eff2-445a-98ff-9f32ea489816
		dataCategory: City
		summarizeBy: none
		sourceColumn: store_city

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column store_state
		dataType: string
		lineageTag: 62745a47-175d-4031-ac13-2b05178533fe
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: store_state

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column store_country
		dataType: string
		lineageTag: 89e870b9-d989-4707-a1a3-83b9cbfeefb1
		dataCategory: Country
		summarizeBy: none
		sourceColumn: store_country

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column store_phone
		dataType: string
		lineageTag: 113d162c-14d1-4269-9df5-25a7e27de14f
		summarizeBy: none
		sourceColumn: store_phone

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column first_opened_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: c1e8fd99-47e5-4334-ab5b-ff58c655f9a9
		summarizeBy: none
		sourceColumn: first_opened_date

		variation Variation
			isDefault
			relationship: bec8aa12-8675-4081-9112-574ebd9187b7
			defaultHierarchy: LocalDateTable_726d5368-f7a9-427d-a020-0e3b1fd416d2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column last_remodel_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 73344e66-27aa-498b-8476-fe71a06e489c
		summarizeBy: none
		sourceColumn: last_remodel_date

		variation Variation
			isDefault
			relationship: 00a3f6f0-f85a-4e72-9991-4e22976e9c9b
			defaultHierarchy: LocalDateTable_1456dd8a-89a4-4c15-97fa-14ed96222686.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column total_sqft
		dataType: int64
		formatString: 0
		lineageTag: 70a6f673-fde7-4d20-ac39-42bd968fb43e
		summarizeBy: sum
		sourceColumn: total_sqft

		annotation SummarizationSetBy = Automatic

	column grocery_sqft
		dataType: int64
		formatString: 0
		lineageTag: f3638b74-92e7-4473-b9c9-0b23e32413ae
		summarizeBy: sum
		sourceColumn: grocery_sqft

		annotation SummarizationSetBy = Automatic

	column full_address
		dataType: string
		lineageTag: 4f1ab1a7-8140-4d9e-af1a-b0b50b22797e
		dataCategory: Address
		summarizeBy: none
		sourceColumn: full_address

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column area_code
		dataType: string
		lineageTag: 3b35683b-464f-402c-8960-13cbfc06cae2
		summarizeBy: none
		sourceColumn: area_code

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Years_Since_Remodel = DATEDIFF(Stores[last_remodel_date],TODAY(),YEAR)
		formatString: 0
		lineageTag: b8c2689f-732c-427f-b181-493fa46d461b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Stores-0fd6072a-a071-4516-80be-8f313408c221 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Chris\Documents\SecondLens\Excel Maven\Udemy\Course 5 - Power BI Desktop\Final Resources\Maven Market\MavenMarket_Stores.csv"),[Delimiter=",", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"store_id", Int64.Type}, {"region_id", Int64.Type}, {"store_type", type text}, {"store_name", type text}, {"store_street_address", type text}, {"store_city", type text}, {"store_state", type text}, {"store_country", type text}, {"store_phone", type text}, {"first_opened_date", type date}, {"last_remodel_date", type date}, {"total_sqft", Int64.Type}, {"grocery_sqft", Int64.Type}}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Changed Type", "full_address", each Text.Combine({[store_street_address], [store_city], [store_state]}, ", "), type text),
				    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Inserted Merged Column", "Text Before Delimiter", each Text.BeforeDelimiter([store_phone], "-"), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Text Before Delimiter",{{"Text Before Delimiter", "area_code"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

