table Stores
	excludeFromModelRefresh
	lineageTag: ea6d48dd-9dc5-4311-91ed-f70707f5c9df

	column store_id
		dataType: int64
		formatString: 0
		lineageTag: 94601d82-0cc9-46a1-927a-026ddeafd9f9
		summarizeBy: none
		sourceColumn: store_id

		annotation SummarizationSetBy = Automatic

	column region_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 91101489-60b3-4f11-877c-296a5ecde934
		summarizeBy: none
		sourceColumn: region_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column store_type
		dataType: string
		lineageTag: a9470a80-fa09-4306-a86a-4331fa19d076
		summarizeBy: none
		sourceColumn: store_type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column store_name
		dataType: string
		lineageTag: 5fb7278e-f88f-4b92-851c-327d48a5e57a
		summarizeBy: none
		sourceColumn: store_name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column store_street_address
		dataType: string
		lineageTag: 9b0e9362-27a5-4e08-8737-38346d0fc443
		summarizeBy: none
		sourceColumn: store_street_address

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column store_city
		dataType: string
		lineageTag: 912d7344-6a7a-45fd-ab33-f3051e99e1f4
		dataCategory: City
		summarizeBy: none
		sourceColumn: store_city

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column store_state
		dataType: string
		lineageTag: 974d7069-5ca1-4ccb-a110-3ad539eebe8d
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: store_state

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column store_country
		dataType: string
		lineageTag: f1b9ec35-3963-4be6-b365-a7c5f120b6fc
		dataCategory: Country
		summarizeBy: none
		sourceColumn: store_country

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column store_phone
		dataType: string
		lineageTag: a715075e-577a-4add-8cbc-a35404a6aa6b
		summarizeBy: none
		sourceColumn: store_phone

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column first_opened_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: ff294cd7-e421-4812-b1d6-e36700eb8ec1
		summarizeBy: none
		sourceColumn: first_opened_date

		variation Variation
			isDefault
			relationship: bec8aa12-8675-4081-9112-574ebd9187b7
			defaultHierarchy: LocalDateTable_726d5368-f7a9-427d-a020-0e3b1fd416d2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column last_remodel_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 298125a7-c698-4420-aef6-82c36daa43c5
		summarizeBy: none
		sourceColumn: last_remodel_date

		variation Variation
			isDefault
			relationship: 00a3f6f0-f85a-4e72-9991-4e22976e9c9b
			defaultHierarchy: LocalDateTable_1456dd8a-89a4-4c15-97fa-14ed96222686.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column total_sqft
		dataType: int64
		formatString: 0
		lineageTag: 979c747d-3cb2-4366-a971-e2276c460b75
		summarizeBy: sum
		sourceColumn: total_sqft

		annotation SummarizationSetBy = Automatic

	column grocery_sqft
		dataType: int64
		formatString: 0
		lineageTag: 3ba9847d-dfb1-4753-b437-f88e9aa05ac3
		summarizeBy: sum
		sourceColumn: grocery_sqft

		annotation SummarizationSetBy = Automatic

	column full_address
		dataType: string
		lineageTag: 83a5f98c-7608-4c11-8def-42ff93383da0
		dataCategory: Address
		summarizeBy: none
		sourceColumn: full_address

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column area_code
		dataType: string
		lineageTag: c38372fa-c036-4295-a14e-484dc2aa67ea
		summarizeBy: none
		sourceColumn: area_code

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Years_Since_Remodel = DATEDIFF(Stores[last_remodel_date],TODAY(),YEAR)
		formatString: 0
		lineageTag: 54c71756-6875-4d4b-ab92-dd9d2c11da69
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Stores-0fd6072a-a071-4516-80be-8f313408c221 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Chris\Documents\SecondLens\Excel Maven\Udemy\Course 5 - Power BI Desktop\Final Resources\Maven Market\MavenMarket_Stores.csv"),[Delimiter=",", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"store_id", Int64.Type}, {"region_id", Int64.Type}, {"store_type", type text}, {"store_name", type text}, {"store_street_address", type text}, {"store_city", type text}, {"store_state", type text}, {"store_country", type text}, {"store_phone", type text}, {"first_opened_date", type date}, {"last_remodel_date", type date}, {"total_sqft", Int64.Type}, {"grocery_sqft", Int64.Type}}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Changed Type", "full_address", each Text.Combine({[store_street_address], [store_city], [store_state]}, ", "), type text),
				    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Inserted Merged Column", "Text Before Delimiter", each Text.BeforeDelimiter([store_phone], "-"), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Text Before Delimiter",{{"Text Before Delimiter", "area_code"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

