table Transaction_Data
	lineageTag: f7c33202-ac8e-4704-afb7-d4acd4b228bf

	measure 'Quantity Sold' = SUM(Transaction_Data[quantity])
		formatString: 0
		lineageTag: 6c405628-55a0-40fc-81f3-c45f7f70741b

	measure 'Total Transactions' = COUNTROWS(Transaction_Data)
		formatString: #,0
		lineageTag: f86d9b21-ec4d-445f-853a-e4b5efa614d9

	measure 'Weekend Transactions' = CALCULATE([Total Transactions], 'Calendar'[Weekend] = "Y")
		formatString: 0
		lineageTag: 6aeb3e88-4477-4ad5-9158-759cde5aab79

	measure '% Weekend Transactions' = [Weekend Transactions] / [Total Transactions]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 389c5456-aed9-4cfe-81eb-2a012b344358

	measure 'All Transactions' = CALCULATE([Total Transactions], ALL(Transaction_Data))
		formatString: 0
		lineageTag: dea5e72c-1f2c-4c8e-838a-14d387321745

	measure 'Total Revenue' = SUMX(Transaction_Data, Transaction_Data[quantity] * RELATED(Products[product_retail_price]))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 05de6561-0439-45e7-ad61-d8f733abc673

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Total Cost' = SUMX(Transaction_Data, Transaction_Data[quantity] * RELATED(Products[product_cost]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: e6e61e4c-778e-45a1-9c99-9cb04f656288

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Total Profit' = [Total Revenue] - [Total Cost]
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a0cda1d3-d33b-4455-9441-57246e675686

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YTD Revenue' = CALCULATE([Total Revenue], DATESYTD('Calendar'[date]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: eb5664de-34a2-4bf8-9a5a-a0168445d1af

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure '60-Day Revenue' = CALCULATE([Total Revenue], DATESINPERIOD('Calendar'[date], MAX('Calendar'[date]),-60,DAY))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 0f0ce953-92ca-4ca8-872f-c1f9c8d77f3c

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Last Month Revenue' = CALCULATE([Total Revenue], DATEADD('Calendar'[date],-1,MONTH))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: ade594e1-a5d7-4624-89fd-80abc9313fc8

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Revenue Target' = [Last Month Revenue] * 1.05
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 6c711707-e7b0-4c3a-96c4-e2e7e96140a7

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Profit Margin' = [Total Profit] / [Total Revenue]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ecd38f3b-7c15-41fc-9957-2ab5179dda25

	measure 'Last Month Transactions' = CALCULATE([Total Transactions], DATEADD('Calendar'[date],-1,MONTH))
		formatString: #,0
		lineageTag: 2da74802-340b-4b78-86b8-2330c2d76414

	measure 'Last Month Profit' = CALCULATE([Total Profit], DATEADD('Calendar'[date],-1,MONTH))
		lineageTag: 5f0e1c4d-504b-46b7-b828-a9b8a02f7f10

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column transaction_date
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: 89ca3681-09e5-4dd6-a896-8c4b1e70d238
		summarizeBy: none
		sourceColumn: transaction_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column stock_date
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: def24c5e-7e38-4048-b8de-b0389d35479a
		summarizeBy: none
		sourceColumn: stock_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column product_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8e66b049-edf1-4b44-8685-7fef87aaaf77
		summarizeBy: none
		sourceColumn: product_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 9d065ff5-8f39-4912-b0ef-37caafe3ab59
		summarizeBy: none
		sourceColumn: customer_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column store_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 04d9d360-cd5a-4c54-8faa-f4f2f403b5f7
		summarizeBy: none
		sourceColumn: store_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: 18e40f43-179f-41ba-aacf-063d2a640567
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	partition Transaction_Data-85b0ae55-8952-4c57-bf7e-b9e435675519 = m
		mode: import
		source =
				let
				    Source = Folder.Files("C:\Users\Chris\Documents\SecondLens\Excel Maven\Udemy\Course 5 - Power BI Desktop\Final Resources\Maven Market\MavenMarket_Transactions"),
				    #"Invoke Custom Function1" = Table.AddColumn(Source, "Transform File from MavenMarket_Transactions", each #"Transform File from MavenMarket_Transactions"([Content])),
				    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File from MavenMarket_Transactions"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File from MavenMarket_Transactions", Table.ColumnNames(#"Transform File from MavenMarket_Transactions"(#"Sample File"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"transaction_date", type date}, {"stock_date", type date}, {"product_id", Int64.Type}, {"customer_id", Int64.Type}, {"store_id", Int64.Type}, {"quantity", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Source.Name"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

