table Customers
	excludeFromModelRefresh
	lineageTag: 05680cc5-8477-4104-8b3d-1d432b35ed93

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: beca27f7-5b60-4d8b-80a6-146f22cb6871
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_acct_num
		dataType: string
		lineageTag: 1b694f2d-a448-4df6-bf27-5981f9226ab3
		summarizeBy: none
		sourceColumn: customer_acct_num

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column first_name
		dataType: string
		lineageTag: 5c6a8e77-654c-4260-b797-bc01572d3f3d
		summarizeBy: none
		sourceColumn: first_name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column last_name
		dataType: string
		lineageTag: 360e5a84-30a1-4ca7-9b8a-88327a3d2bd2
		summarizeBy: none
		sourceColumn: last_name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column customer_address
		dataType: string
		lineageTag: 9894f6d8-ba4b-4428-af83-f26cbde3b62f
		summarizeBy: none
		sourceColumn: customer_address

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column customer_city
		dataType: string
		lineageTag: 153044f4-2a66-4369-976a-31dbefac4b0f
		dataCategory: City
		summarizeBy: none
		sourceColumn: customer_city

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column customer_state_province
		dataType: string
		lineageTag: d713ff42-4c9e-46d0-bc2d-c007178f8a33
		summarizeBy: none
		sourceColumn: customer_state_province

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column customer_postal_code
		dataType: string
		lineageTag: fb9ffe87-356e-413f-9edf-371e2a980579
		dataCategory: PostalCode
		summarizeBy: none
		sourceColumn: customer_postal_code

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column customer_country
		dataType: string
		lineageTag: 6281ce25-ebd6-48ef-85a8-6068b94d083c
		dataCategory: Country
		summarizeBy: none
		sourceColumn: customer_country

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column birthdate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 798f542f-e6c1-4ae7-9f5e-523cc6b77bc0
		summarizeBy: none
		sourceColumn: birthdate

		variation Variation
			isDefault
			relationship: 7b96ac4e-aafe-40c4-985d-e27d16f3e6b2
			defaultHierarchy: LocalDateTable_c5a3a9d6-4c73-4de9-b37b-a0dc9d8b563a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column marital_status
		dataType: string
		lineageTag: 895176d3-1cbc-4f18-a531-8989f60184f3
		summarizeBy: none
		sourceColumn: marital_status

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column yearly_income
		dataType: string
		lineageTag: aeb0b824-c193-4379-b470-244d1a8bc9dd
		summarizeBy: none
		sourceColumn: yearly_income

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column gender
		dataType: string
		lineageTag: 5e7ac300-0520-4abe-8ad6-d51690e9ca75
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column total_children
		dataType: int64
		formatString: 0
		lineageTag: 2f643b60-352e-42e0-976b-f7090eee665d
		summarizeBy: sum
		sourceColumn: total_children

		annotation SummarizationSetBy = Automatic

	column num_children_at_home
		dataType: int64
		formatString: 0
		lineageTag: 7240202c-f6c4-4709-b040-2b10827da1b3
		summarizeBy: sum
		sourceColumn: num_children_at_home

		annotation SummarizationSetBy = Automatic

	column education
		dataType: string
		lineageTag: 1cd5a630-d110-4d76-a4ee-ba7c50e509b7
		summarizeBy: none
		sourceColumn: education

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column acct_open_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: bc594ab7-b321-40ab-98eb-2097735a3e72
		summarizeBy: none
		sourceColumn: acct_open_date

		variation Variation
			isDefault
			relationship: d621e994-1174-4115-9eda-17adddd90fa1
			defaultHierarchy: LocalDateTable_fe5a205d-33f0-43f0-bde9-d805094d7108.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column member_card
		dataType: string
		lineageTag: 256a9109-02fe-4ea8-8759-4e5890fa309f
		summarizeBy: none
		sourceColumn: member_card

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column occupation
		dataType: string
		lineageTag: 6d899388-af65-48d6-a24a-28ab7a61b95c
		summarizeBy: none
		sourceColumn: occupation

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column homeowner
		dataType: string
		lineageTag: 2cc1050f-7528-4f49-818b-820d13d02daa
		summarizeBy: none
		sourceColumn: homeowner

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column full_name
		dataType: string
		lineageTag: 630fa7a4-f255-4b19-8017-9aaaff1457c7
		summarizeBy: none
		sourceColumn: full_name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column birth_year
		dataType: int64
		formatString: 0
		lineageTag: f8248873-fcf1-4880-bd69-ad37f2026ca9
		summarizeBy: sum
		sourceColumn: birth_year

		annotation SummarizationSetBy = Automatic

	column has_children
		dataType: string
		lineageTag: 43126cc5-1c9b-4aca-bb8b-fff592f56cbc
		summarizeBy: none
		sourceColumn: has_children

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Current_Age = DATEDIFF(Customers[birthdate],TODAY(),YEAR)
		formatString: 0
		lineageTag: efa80d0c-2d9a-4b75-a133-c72b29f8b988
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Priority = IF(Customers[member_card] = "Golden" && Customers[homeowner] = "Y","High","Standard")
		lineageTag: 17e6229f-80b7-4bdb-95ad-4d6f57726fcc
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Short_Country = UPPER(LEFT(Customers[customer_country],3))
		lineageTag: 4eca1abd-8767-4901-85da-3d198817929c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column House_Number = LEFT(Customers[customer_address], SEARCH(" ", Customers[customer_address])-1)
		lineageTag: 273beab7-4e6f-4432-bc15-0a0ef7ff43f6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition Customers-06ce47fd-0986-4c0a-b7fb-60681980529d = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Grace\Official\interviewquesndans\pbip\MavenMarket_Customers.csv"),[Delimiter=",", Columns=20, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", Int64.Type}, {"customer_acct_num", type text}, {"first_name", type text}, {"last_name", type text}, {"customer_address", type text}, {"customer_city", type text}, {"customer_state_province", type text}, {"customer_postal_code", type text}, {"customer_country", type text}, {"birthdate", type date}, {"marital_status", type text}, {"yearly_income", type text}, {"gender", type text}, {"total_children", Int64.Type}, {"num_children_at_home", Int64.Type}, {"education", type text}, {"acct_open_date", type date}, {"member_card", type text}, {"occupation", type text}, {"homeowner", type text}}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Changed Type", "full_name", each Text.Combine({[first_name], [last_name]}, " "), type text),
				    #"Inserted Year" = Table.AddColumn(#"Inserted Merged Column", "Year", each Date.Year([birthdate]), Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Year",{{"Year", "birth_year"}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Renamed Columns", "has_children", each if [total_children] = 0 then "N" else "Y")
				in
				    #"Added Conditional Column"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

