table Regions
	excludeFromModelRefresh
	lineageTag: 0ac12219-6766-49f9-bccd-65852d952f19

	column region_id
		dataType: int64
		formatString: 0
		lineageTag: f7339ab1-d31c-4da3-b952-7862d3ca02a5
		summarizeBy: none
		sourceColumn: region_id

		annotation SummarizationSetBy = Automatic

	column sales_district
		dataType: string
		lineageTag: db02d442-5a18-44bf-b1e5-f242c4fc4c41
		summarizeBy: none
		sourceColumn: sales_district

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column sales_region
		dataType: string
		lineageTag: 28a19c54-7cc5-4f8f-8aca-d5cf5f645c50
		summarizeBy: none
		sourceColumn: sales_region

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition Regions-7d79bf32-5383-4a2e-b645-3b4c2dde808f = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Grace\Official\interviewquesndans\pbip\MavenMarket_Regions.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"region_id", Int64.Type}, {"sales_district", type text}, {"sales_region", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

